const mongoose=require("mongoose");

const eventSchema=new mongoose.Schema({
     eventName:{
        type:String,
        required:true,
     },
     TeacherEmail:{//teacher id from teacherSchema ref to objId
        type:String,
        required:true
     },
     hostingCollege:{
        type:String,
        required:true
     },
     participatingColleges:{
        type:[String],
        default:[]
     },
     participatingStudents:{
       type:[String],
       default:[]
     },
     sportsCategory:{
        type:[String],
        required:true
     },
     selectedStudents:[{
      selectedSport:{
         type:String
      },
      studentInfo:[{
       studentId:String,
       profilePic:String,
       name:String,
       email:String,
       collegeName:String,
       gender:String,
       participatingSports:[String],
     }]}],
     result:[{
      selectedSport:{
         type:String
      },
      winnerStudentInfo:{
         studentId:String,
         profilePic:String,
         name:String,
         email:String,
         collegeName:String,
         gender:String,
         participatingSports:[String],
      },
      runnersUpStudentInfo:{
         studentId:String,
         profilePic:String,
         name:String,
         email:String,
         collegeName:String,
         gender:String,
         participatingSports:[String],
      }
     }],
     moderators:[{
       sport:String,
       moderatorDetails:{
         name:String,
         email:String,
         password:String,
       }
     }],
     liveScore:[{
      sport:String,
      score:{
         matchBetween:{
            team1:String,
            team2:String
         },
         presentScore:{
            team1Score:String,
            team2Score:String,
         },
         commentary:String,
      }
     }],
     venue:{
        type:String,
        required:true,
     },
     eventBanner:{
      type:String,
     }
});

const eventCollection=new mongoose.model("eventcolleciton",eventSchema);
module.exports=eventCollection;